// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace HexArch.Services.Specs.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class UserRegistrationFeature : object, Xunit.IClassFixture<UserRegistrationFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Xunit.ITestOutputHelper _testOutputHelper;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "User registration", "\tAs a visitor to HexArch\r\n\tI want to register an account with my name, email, pas" +
                "sword and mobile number\r\n\tSo that I can sign in and shop", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "RegisterUser.feature"
#line hidden
        
        public UserRegistrationFeature(UserRegistrationFeature.FixtureData fixtureData, Xunit.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
#line hidden
#line 7
 await testRunner.GivenAsync("the default \"Customer\" role is configured", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
 await testRunner.AndAsync("the system clock is fixed at \"2026-08-20T10:30:00Z\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/RegisterUser.feature.ndjson", 14);
        }
        
        async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="A visitor registers with valid details")]
        [global::Xunit.TraitAttribute("FeatureTitle", "User registration")]
        [global::Xunit.TraitAttribute("Description", "A visitor registers with valid details")]
        public async global::System.Threading.Tasks.Task AVisitorRegistersWithValidDetails()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A visitor registers with valid details", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 10
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Email",
                            "Password",
                            "MobileNo"});
                table1.AddRow(new string[] {
                            "Nikhil Patel",
                            "nikhil@example.com",
                            "Sup3rSecret!",
                            "9876543210"});
#line 11
 await testRunner.WhenAsync("I register with the following details:", ((string)(null)), table1, "When ");
#line hidden
#line 14
 await testRunner.ThenAsync("the registration succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 15
 await testRunner.AndAsync("the new account is returned with an identifier", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
 await testRunner.AndAsync("an account exists for \"nikhil@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
 await testRunner.AndAsync("that account is active", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
 await testRunner.AndAsync("that account is registered on \"2026-08-20T10:30:00Z\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
 await testRunner.AndAsync("that account is granted the \"Customer\" role", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="The password is never stored in plain text")]
        [global::Xunit.TraitAttribute("FeatureTitle", "User registration")]
        [global::Xunit.TraitAttribute("Description", "The password is never stored in plain text")]
        public async global::System.Threading.Tasks.Task ThePasswordIsNeverStoredInPlainText()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The password is never stored in plain text", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 21
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Email",
                            "Password",
                            "MobileNo"});
                table2.AddRow(new string[] {
                            "Nikhil Patel",
                            "nikhil@example.com",
                            "Sup3rSecret!",
                            "9876543210"});
#line 22
 await testRunner.WhenAsync("I register with the following details:", ((string)(null)), table2, "When ");
#line hidden
#line 25
 await testRunner.ThenAsync("the registration succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 26
 await testRunner.AndAsync("the stored password for \"nikhil@example.com\" is not \"Sup3rSecret!\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
 await testRunner.AndAsync("the stored password for \"nikhil@example.com\" is salted", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Registering announces the new account to the rest of the system")]
        [global::Xunit.TraitAttribute("FeatureTitle", "User registration")]
        [global::Xunit.TraitAttribute("Description", "Registering announces the new account to the rest of the system")]
        public async global::System.Threading.Tasks.Task RegisteringAnnouncesTheNewAccountToTheRestOfTheSystem()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registering announces the new account to the rest of the system", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 29
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Email",
                            "Password",
                            "MobileNo"});
                table3.AddRow(new string[] {
                            "Nikhil Patel",
                            "nikhil@example.com",
                            "Sup3rSecret!",
                            "9876543210"});
#line 30
 await testRunner.WhenAsync("I register with the following details:", ((string)(null)), table3, "When ");
#line hidden
#line 33
 await testRunner.ThenAsync("the registration succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 34
 await testRunner.AndAsync("a \"UserRegistered\" event is published for the new account", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
 await testRunner.AndAsync("that event occurred on \"2026-08-20T10:30:00Z\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="The email address is already registered")]
        [global::Xunit.TraitAttribute("FeatureTitle", "User registration")]
        [global::Xunit.TraitAttribute("Description", "The email address is already registered")]
        public async global::System.Threading.Tasks.Task TheEmailAddressIsAlreadyRegistered()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The email address is already registered", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 37
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 38
 await testRunner.GivenAsync("an account already exists for \"nikhil@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Email",
                            "Password",
                            "MobileNo"});
                table4.AddRow(new string[] {
                            "Nikhil Patel",
                            "nikhil@example.com",
                            "Sup3rSecret!",
                            "9876543210"});
#line 39
 await testRunner.WhenAsync("I register with the following details:", ((string)(null)), table4, "When ");
#line hidden
#line 42
 await testRunner.ThenAsync("the registration fails with the error \"A user with this email is already register" +
                        "ed.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 43
 await testRunner.AndAsync("no new account is stored", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 44
 await testRunner.AndAsync("no event is published", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="The default role has not been configured")]
        [global::Xunit.TraitAttribute("FeatureTitle", "User registration")]
        [global::Xunit.TraitAttribute("Description", "The default role has not been configured")]
        public async global::System.Threading.Tasks.Task TheDefaultRoleHasNotBeenConfigured()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The default role has not been configured", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 46
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 47
 await testRunner.GivenAsync("the default \"Customer\" role is not configured", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Email",
                            "Password",
                            "MobileNo"});
                table5.AddRow(new string[] {
                            "Nikhil Patel",
                            "nikhil@example.com",
                            "Sup3rSecret!",
                            "9876543210"});
#line 48
 await testRunner.WhenAsync("I register with the following details:", ((string)(null)), table5, "When ");
#line hidden
#line 51
 await testRunner.ThenAsync("the registration fails with the error \"Default role \'Customer\' is not configured." +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 52
 await testRunner.AndAsync("no new account is stored", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 53
 await testRunner.AndAsync("no event is published", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.TheoryAttribute(DisplayName="A required detail is missing or invalid")]
        [global::Xunit.TraitAttribute("FeatureTitle", "User registration")]
        [global::Xunit.TraitAttribute("Description", "A required detail is missing or invalid")]
        [global::Xunit.InlineDataAttribute("", "nikhil@example.com", "Sup3rSecret!", "9876543210", "Name is required.", "5", new string[0])]
        [global::Xunit.InlineDataAttribute("Nikhil Patel", "", "Sup3rSecret!", "9876543210", "A valid email is required.", "6", new string[0])]
        [global::Xunit.InlineDataAttribute("Nikhil Patel", "not-an-email", "Sup3rSecret!", "9876543210", "A valid email is required.", "7", new string[0])]
        [global::Xunit.InlineDataAttribute("Nikhil Patel", "nikhil@example.com", "", "9876543210", "Password must be at least 8 characters long.", "8", new string[0])]
        [global::Xunit.InlineDataAttribute("Nikhil Patel", "nikhil@example.com", "Sh0rt", "9876543210", "Password must be at least 8 characters long.", "9", new string[0])]
        [global::Xunit.InlineDataAttribute("Nikhil Patel", "nikhil@example.com", "Sup3rSecret!", "", "Mobile number is required.", "10", new string[0])]
        public async global::System.Threading.Tasks.Task ARequiredDetailIsMissingOrInvalid(string name, string email, string password, string mobileNo, string error, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("name", name);
            argumentsOfScenario.Add("email", email);
            argumentsOfScenario.Add("password", password);
            argumentsOfScenario.Add("mobileNo", mobileNo);
            argumentsOfScenario.Add("error", error);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A required detail is missing or invalid", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 55
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Email",
                            "Password",
                            "MobileNo"});
                table6.AddRow(new string[] {
                            string.Format("{0}", name),
                            string.Format("{0}", email),
                            string.Format("{0}", password),
                            string.Format("{0}", mobileNo)});
#line 56
 await testRunner.WhenAsync("I register with the following details:", ((string)(null)), table6, "When ");
#line hidden
#line 59
 await testRunner.ThenAsync(string.Format("the registration fails with the error \"{0}\"", error), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 60
 await testRunner.AndAsync("no new account is stored", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 61
 await testRunner.AndAsync("no event is published", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Every invalid detail is reported at once")]
        [global::Xunit.TraitAttribute("FeatureTitle", "User registration")]
        [global::Xunit.TraitAttribute("Description", "Every invalid detail is reported at once")]
        public async global::System.Threading.Tasks.Task EveryInvalidDetailIsReportedAtOnce()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Every invalid detail is reported at once", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 72
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Email",
                            "Password",
                            "MobileNo"});
                table7.AddRow(new string[] {
                            "",
                            "",
                            "",
                            ""});
#line 73
 await testRunner.WhenAsync("I register with the following details:", ((string)(null)), table7, "When ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "Error"});
                table8.AddRow(new string[] {
                            "Name is required."});
                table8.AddRow(new string[] {
                            "A valid email is required."});
                table8.AddRow(new string[] {
                            "Password must be at least 8 characters long."});
                table8.AddRow(new string[] {
                            "Mobile number is required."});
#line 76
 await testRunner.ThenAsync("the registration fails with these errors:", ((string)(null)), table8, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
            {
                await UserRegistrationFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
            {
                await UserRegistrationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
